version: '3'
services:
    portainer:
        build: ./portainer
        ports:
         - "9000:9000"
        command: -H unix:///var/run/docker.sock
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data

volumes:
    - portainer_data: /opt/portainer

networks:
    external:
    name: "${s_net}"
