version: '3'
services:
    plex:
        container_name: plex
        image: plexinc/pms-docker
        volumes:
            - ../volumes/plex/config:/config
            - ../volumes/common/movies:/data/
        network_mode: "host"
        restart: always
    owncloud:
        container_name: owncloud
        image: owncloud
        restart: always
        ports:
            - "9001:80"
        depends_on:
            - mariadb
        volumes:
            - ../volumes/owncloud/apps:/var/www/html/apps
            - ../volumes/owncloud/config:/var/www/html/config
            - ../volumes/owncloud/data:/var/www/html/data
            - ../volumes/common/movies:/var/www/html/data/plex
        networks:
            - openpantoufle
    mariadb:
        container_name: mariadb
        env_file:
            - mariadb.env
        image: mariadb
        restart: always
        ports:
            - "9002:3306"
        volumes:
            - owncloud-data:/var/lib/mysql
            - ./mariadb:/docker-entrypoint-initdb.d
        networks:
            - openpantoufle
    minecraft:
        container_name: minecraft
        build:
            context: ./minecraft
            dockerfile: Dockerfile
        restart: always
        ports:
            - "25565:25565"
            - "9003:8080"
        volumes:
            - ../volumes/common/minecraft:/root/Minecraft/world
        networks:
            - openpantoufle
networks:
    openpantoufle:
        driver: bridge
volumes:
    owncloud-data: {}
